services:
  db:
    image: postgres:16
    container_name: autoflex-db
    environment:
      POSTGRES_DB: autoflex
      POSTGRES_USER: autoflex
      POSTGRES_PASSWORD: autoflex
    ports:
      - "5432:5432"
    volumes:
      - autoflex_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autoflex -d autoflex"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: autoflex-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_DATASOURCE_USERNAME: autoflex
      QUARKUS_DATASOURCE_PASSWORD: autoflex
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/autoflex
      QUARKUS_HTTP_CORS: "true"
      QUARKUS_HTTP_CORS_ORIGINS: http://localhost:5173
      QUARKUS_HTTP_CORS_METHODS: GET,POST,PUT,DELETE,OPTIONS
      QUARKUS_HTTP_CORS_HEADERS: accept,authorization,content-type,x-requested-with
      QUARKUS_FLYWAY_MIGRATE_AT_START: "true"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: autoflex-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  autoflex_pgdata:
